# Generated by Django 4.0.5 on 2022-06-22 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_category_description_category_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='discount',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
