# Generated by Django 4.0.5 on 2022-06-26 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_product_discount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('mail', models.CharField(max_length=30)),
                ('phone', models.CharField(max_length=11)),
                ('text', models.TextField()),
            ],
        ),
    ]
