# Generated by Django 4.0.5 on 2022-06-26 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_contact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='mail',
            new_name='email',
        ),
    ]
