# Generated by Django 4.0.5 on 2022-07-07 15:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0013_alter_shop_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shop_client', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='shopitems',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_product', to='main.product'),
        ),
        migrations.AlterField(
            model_name='shopitems',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_savatcha', to='main.shop'),
        ),
    ]
