# Generated by Django 4.0.1 on 2022-07-17 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_remove_shopitems_total_shopitems_totalpay_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shipping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('region', models.CharField(choices=[('Andijan', 'Andijan'), ('Namangan', 'Namangan'), ('Fergana', 'Fergana'), ('Tashkent', 'Tashkent'), ('Tashkent city', 'Tashkent city'), ('Sirdaryo', 'Sirdaryo'), ('Jizzakh', 'Jizzakh'), ('Qashkadarya', 'Qashkadarya'), ('Surkhandarya', 'Surkhandarya'), ('Samarkand', 'Samarkand'), ('Navaiy', 'Navaiy'), ('Bukhara', 'Bukhara'), ('Khorazm', 'Khorazm'), ('Karakalpagistan', 'Karakalpagistan')], max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=300)),
                ('zipcode', models.IntegerField()),
                ('phone', models.IntegerField(max_length=11)),
            ],
        ),
    ]
