# Generated by Django 4.0.1 on 2022-08-29 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_shipping'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='categ/'),
        ),
        migrations.AlterField(
            model_name='shipping',
            name='phone',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='shipping',
            name='region',
            field=models.CharField(max_length=200),
        ),
    ]
