# Generated by Django 4.0.1 on 2022-10-04 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_alter_category_description_alter_category_photo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='category',
            name='photo',
            field=models.ImageField(default=1, upload_to='categ/'),
            preserve_default=False,
        ),
    ]
